//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CicOData
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentStat
    {
        public string campaignname { get; set; }
        public string siteid { get; set; }
        public int odsoffset { get; set; }
        public System.DateTime agenttimeUTC { get; set; }
        public string agentid { get; set; }
        public string stageid { get; set; }
        public string callid { get; set; }
        public string callidkey { get; set; }
        public string propertyname { get; set; }
        public string propertyvalue { get; set; }
    }
}
