//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CicOData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallHistory
    {
        public string campaignname { get; set; }
        public string siteid { get; set; }
        public Nullable<long> i3_identity { get; set; }
        public string i3_rowid { get; set; }
        public string callid { get; set; }
        public string callidkey { get; set; }
        public string wrapupcategory { get; set; }
        public string wrapupcode { get; set; }
        public Nullable<byte> callingmode { get; set; }
        public string phonenumber { get; set; }
        public string phonenumbertype { get; set; }
        public string agentid { get; set; }
        public Nullable<int> calledpartyoffset { get; set; }
        public int odsoffset { get; set; }
        public Nullable<System.DateTime> previewpoptimeUTC { get; set; }
        public Nullable<System.DateTime> callplacedtimeUTC { get; set; }
        public Nullable<System.DateTime> callansweredtimeUTC { get; set; }
        public Nullable<System.DateTime> messageplaytimeUTC { get; set; }
        public Nullable<System.DateTime> callconnectedtimeUTC { get; set; }
        public System.DateTime calldisconnectedtimeUTC { get; set; }
        public Nullable<int> length { get; set; }
        public Nullable<byte> caresult { get; set; }
        public string cadetail { get; set; }
        public Nullable<bool> isabandoned { get; set; }
        public Nullable<bool> iscontact { get; set; }
        public Nullable<bool> isdetect { get; set; }
        public Nullable<bool> isrpc { get; set; }
        public Nullable<bool> issuccess { get; set; }
        public Nullable<double> successresult { get; set; }
        public string customdata1 { get; set; }
        public string customdata2 { get; set; }
        public Nullable<short> campaignfilterid { get; set; }
    }
}
