//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CicOData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampaignStat
    {
        public System.DateTime periodstarttimeUTC { get; set; }
        public System.DateTime periodendtimeUTC { get; set; }
        public int odsoffset { get; set; }
        public string campaignname { get; set; }
        public string siteid { get; set; }
        public string @event { get; set; }
        public string campaignstate { get; set; }
        public string dialingmode { get; set; }
        public int filtersize { get; set; }
        public int recyclesize { get; set; }
        public int totalagents { get; set; }
        public double effectivetotalagents { get; set; }
        public int idleagents { get; set; }
        public double effectiveidleagents { get; set; }
        public int nondialeragents { get; set; }
        public int dndagents { get; set; }
        public int totaldialercalls { get; set; }
        public Nullable<int> pace { get; set; }
        public Nullable<double> cpa { get; set; }
        public Nullable<double> adjcpa { get; set; }
        public Nullable<double> abandonrate { get; set; }
        public byte priority { get; set; }
    }
}
