//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CicOData
{
    using System;
    using System.Collections.Generic;
    
    public partial class InteractionSummary
    {
        public string InteractionIDKey { get; set; }
        public short SiteID { get; set; }
        public byte SeqNo { get; set; }
        public long InteractionID { get; set; }
        public System.DateTime StartDateTimeUTC { get; set; }
        public int StartDTOffset { get; set; }
        public byte Direction { get; set; }
        public byte ConnectionType { get; set; }
        public byte MediaType { get; set; }
        public string RemoteID { get; set; }
        public string DNIS_LocalID { get; set; }
        public Nullable<int> tDialing { get; set; }
        public Nullable<int> tIVRWait { get; set; }
        public Nullable<decimal> tQueueWait { get; set; }
        public Nullable<int> tAlert { get; set; }
        public Nullable<decimal> tConnected { get; set; }
        public Nullable<decimal> tHeld { get; set; }
        public Nullable<decimal> tSuspend { get; set; }
        public Nullable<decimal> tConference { get; set; }
        public Nullable<decimal> tExternal { get; set; }
        public Nullable<int> tACW { get; set; }
        public Nullable<short> nIVR { get; set; }
        public Nullable<short> nQueueWait { get; set; }
        public Nullable<short> nTalk { get; set; }
        public Nullable<short> nConference { get; set; }
        public Nullable<short> nHeld { get; set; }
        public Nullable<short> nTransfer { get; set; }
        public Nullable<short> nExternal { get; set; }
        public byte Disposition { get; set; }
        public Nullable<byte> DispositionCode { get; set; }
        public string WrapUpCode { get; set; }
        public string AccountCode { get; set; }
        public bool IsRecorded { get; set; }
        public bool IsSurveyed { get; set; }
        public string MediaServerID { get; set; }
        public string IndivID { get; set; }
        public string OrgID { get; set; }
        public string LineId { get; set; }
        public string LastStationId { get; set; }
        public string LastLocalUserId { get; set; }
        public string LastAssignedWorkgroupID { get; set; }
        public string LastLocalNumber { get; set; }
        public string LastLocalName { get; set; }
        public string RemoteICUserID { get; set; }
        public Nullable<short> RemoteNumberCountry { get; set; }
        public string RemoteNumberLoComp1 { get; set; }
        public string RemoteNumberLoComp2 { get; set; }
        public string RemoteNumberFmt { get; set; }
        public string RemoteNumberCallId { get; set; }
        public string RemoteName { get; set; }
        public System.DateTime InitiatedDateTimeUTC { get; set; }
        public System.DateTime ConnectedDateTimeUTC { get; set; }
        public System.DateTime TerminatedDateTimeUTC { get; set; }
        public Nullable<decimal> LineDuration { get; set; }
        public string CallEventLog { get; set; }
        public Nullable<int> PurposeCode { get; set; }
        public string CallNote { get; set; }
        public short nSecuredIVR { get; set; }
        public Nullable<decimal> tSecuredIVR { get; set; }
        public string FirstAssignedAcdSkillSet { get; set; }
    }
}
